addpath(genpath(fullfile(pwd)))
addpath(genpath(fullfile(pwd,'continuous_submodular_minimization')))
addpath(genpath(fullfile(pwd,'robust_budget_allocation')))
addpath(genpath(fullfile(pwd,'experiments')))
addpath(genpath(fullfile(pwd,'test_suite')))
